// packages/vue/src/ThemeModeProvider.vue
<script setup lang="ts">

import ThemeMode, { type Options, options as defaultOptions } from 'theme-mode'
import { onMounted, provide, shallowReactive, onUnmounted } from 'vue'

const { host, ...options } = withDefaults(defineProps<Options & { host?: HTMLElement }>(), defaultOptions)
const themeMode = shallowReactive<ThemeMode>(new ThemeMode(options, host))
// Trigger reactivity when the theme mode changes
const onThemeModeChange = () => themeMode.value = themeMode.value

onMounted(() => {
    themeMode.init()
    themeMode.host?.addEventListener('themeModeChange', onThemeModeChange, { passive: true })
})
onUnmounted(() => {
    themeMode.destroy()
    themeMode.host?.removeEventListener('themeModeChange', onThemeModeChange)
})

provide('theme-mode', themeMode)

</script>

<template>
    <slot></slot>
</template>

// packages/svelte/src/lib/ThemeModeProvider.svelte
<script lang="ts">
    import { onMount, onDestroy, setContext } from "svelte";
    import { writable } from "svelte/store";
    import ThemeMode, { type Options } from "theme-mode";

    export let options: Options | undefined = undefined;
    export let host: HTMLElement | undefined = undefined;

    const themeMode = writable(new ThemeMode(options, host));
    const onThemeModeChange = () => themeMode.set($themeMode);

    onMount(() => {
        $themeMode.init();
        themeMode.update(() => $themeMode);
        $themeMode.host?.addEventListener(
            "themeModeChange",
            onThemeModeChange,
            { passive: true },
        );
    });

    onDestroy(() => {
        $themeMode.destroy();
        $themeMode.host?.removeEventListener(
            "themeModeChange",
            onThemeModeChange,
        );
    });

    setContext("theme-mode", themeMode);
</script>

<slot />
